### ISSUE TITLE
Babel dependencies not installing

### ISSUE THREAD

**Issue by bpeters** [mindsdb/mindsdb_js_sdk#35]
**Your Environment**

* Mindsdb JS SDK version: "mindsdb-js-sdk": "^0.5.8",
* Operating system: macOS Cataline v10.15.7
* Additional info if applicable: Running Node v14.15.4

**Please describe your issue and how we can replicate it**

Cannot find module '@babel/runtime/helpers/classCallCheck' when importing sdk.

I had to install `@babel/runtime` myself locally

**Comment by abdellani** [comment]
Hi
I think that the problem is not solved.
I also need to install `@babel/runtime` before I could run the following example:
```js
const  MindsDB= require('mindsdb-js-sdk');

const main = async()=>{
  MindsDB.connect("http://127.0.0.1:47334/api", [{key:"apikey",value:"placeholder"}]);
  const connected = await MindsDB.ping();
  if (!connected) return;
  console.log("connected !!!")
}

main();
```
